CREATE TABLE [dbo].[accounts_temp] (
    [Fiscal_Year]                 NUMERIC (4)     NOT NULL,
    [Fiscal_Period]               VARCHAR (2)     NOT NULL,
    [Chart_Num]                   VARCHAR (2)     NOT NULL,
    [Account_Num]                 VARCHAR (7)     NOT NULL,
    [Org_ID]                      VARCHAR (4)     NULL,
    [Account_Name]                VARCHAR (40)    NULL,
    [SubFund_Group_Num]           VARCHAR (6)     NULL,
    [Sub_Fund_Group_Type_Code]    VARCHAR (2)     NULL,
    [Fund_Group_Code]             VARCHAR (2)     NULL,
    [Acct_Effective_Date]         DATETIME2 (7)   NULL,
    [Acct_Create_Date]            DATETIME2 (7)   NULL,
    [Acct_Expiration_Date]        DATETIME2 (7)   NULL,
    [Acct_Last_Update_Date]       DATETIME2 (7)   NULL,
    [Acct_Mgr_Id]                 VARCHAR (8)     NULL,
    [Acct_Mgr_Name]               VARCHAR (30)    NULL,
    [Acct_Reviewer_Id]            VARCHAR (8)     NULL,
    [Acct_Reviewer_Name]          VARCHAR (30)    NULL,
    [Principal_Investigator_Id]   VARCHAR (8)     NULL,
    [Principal_Investigator_Name] VARCHAR (30)    NULL,
    [Acct_Type_Code]              VARCHAR (2)     NULL,
    [Acct_Purpose_Text]           VARCHAR (400)   NULL,
    [Control_Chart_Num]           VARCHAR (2)     NULL,
    [Control_Acct_Num]            VARCHAR (7)     NULL,
    [Sponsor_Code]                VARCHAR (4)     NULL,
    [Sponsor_Category_Code]       VARCHAR (2)     NULL,
    [Federal_Agency_Code]         VARCHAR (2)     NULL,
    [CFDA_Num]                    VARCHAR (6)     NULL,
    [Award_Num]                   VARCHAR (20)    NULL,
    [Award_Type_Code]             VARCHAR (1)     NULL,
    [Award_Year_Num]              VARCHAR (2)     NULL,
    [Award_Begin_Date]            DATETIME2 (7)   NULL,
    [Award_End_Date]              DATETIME2 (7)   NULL,
    [Award_Amount]                NUMERIC (15, 2) NULL,
    [ICR_Type_Code]               VARCHAR (2)     NULL,
    [ICR_Series_Num]              VARCHAR (3)     NULL,
    [Higher_Ed_Func_Code]         VARCHAR (4)     NULL,
    [Acct_Reports_To_Chart_Num]   VARCHAR (2)     NULL,
    [Acct_Reports_To_Acct_Num]    VARCHAR (7)     NULL,
    [A11_Acct_Num]                VARCHAR (7)     NULL,
    [A11_Fund_Num]                VARCHAR (7)     NULL,
    [OP_Fund_Num]                 VARCHAR (6)     NULL,
    [OP_Fund_Group_Code]          VARCHAR (6)     NULL,
    [Academic_Discipline_Code]    VARCHAR (3)     NULL,
    [Annual_Report_Code]          VARCHAR (6)     NULL,
    [Payment_Medium_Code]         VARCHAR (2)     NULL,
    [NIH_Doc_Num]                 VARCHAR (12)    NULL,
    [fringe_benefit_ind]          VARCHAR (1)     NULL,
    [fringe_benefit_chart_num]    VARCHAR (2)     NULL,
    [fringe_benefit_acct_num]     VARCHAR (7)     NULL,
    [Ye_Type]                     INT             NULL,
    [Account_PK]                  VARCHAR (54)    NULL,
    [Org_FK]                      VARCHAR (51)    NULL,
    [FunctionCodeID]              INT             NULL,
    [OPFund_FK]                   VARCHAR (53)    NULL,
    [Is_CAES]                     NVARCHAR (384)  NULL
);

