CREATE TABLE [dbo].[GeneralLedgerProjectBalanceForAllPeriods_temp] (
    [FISCAL_YEAR]                    NUMERIC (4)     NOT NULL,
    [CHART_NUM]                      VARCHAR (2)     NOT NULL,
    [ORG_ID]                         VARCHAR (4)     NULL,
    [ACCT_TYPE_CODE]                 VARCHAR (2)     NULL,
    [ACCT_NUM]                       VARCHAR (7)     NOT NULL,
    [SUB_ACCT_NUM]                   VARCHAR (5)     NOT NULL,
    [OBJ_CONSOLIDATN_NUM]            VARCHAR (4)     NULL,
    [OBJECT_NUM]                     VARCHAR (4)     NOT NULL,
    [SUB_OBJECT_NUM]                 VARCHAR (4)     NOT NULL,
    [PROJECT_NUM]                    VARCHAR (10)    NOT NULL,
    [BALANCE_TYPE_CODE]              VARCHAR (2)     NOT NULL,
    [BALANCE_TYPE_NAME]              VARCHAR (40)    NULL,
    [OBJECT_TYPE_CODE]               VARCHAR (2)     NOT NULL,
    [SUB_FUND_GROUP_TYPE_CODE]       VARCHAR (2)     NULL,
    [BALANCE_CREATE_DATE]            DATETIME2 (7)   NULL,
    [YTD_ACTUAL_AMT]                 NUMERIC (15, 2) NULL,
    [FISCAL_YEAR_BEGIN_BAL]          NUMERIC (15, 2) NULL,
    [CONTRACTS_AND_GRANTS_BEGIN_BAL] NUMERIC (15, 2) NULL,
    [JUL_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [AUG_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [SEP_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [OCT_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [NOV_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [DEC_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [JAN_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [FEB_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [MAR_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [APR_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [MAY_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [JUN_TRANS_TOTAL_AMT]            NUMERIC (15, 2) NULL,
    [MONTH13_TRANS_TOTAL_AMT]        NUMERIC (15, 2) NULL,
    [LAST_UPDATE_DATE]               DATETIME2 (7)   NULL
);

