CREATE TABLE [dbo].[CTO_OSC_StaffType] (
    [TCI_TITLE_CODE]     VARCHAR (4)   NULL,
    [TCI_TITLE_NAME]     VARCHAR (150) NULL,
    [TCI_TITLE_NM_ABBRV] VARCHAR (30)  NULL,
    [TCI_PERSONL_PGM_CD] VARCHAR (1)   NULL,
    [TCI_TITLE_UNIT_CD]  VARCHAR (2)   NULL,
    [STAFFTYPE]          CHAR (2)      NULL,
    [TCI_CTO_OSC]        VARCHAR (3)   NULL,
    [TCI_FOC]            VARCHAR (1)   NULL,
    [TCI_FOC_SUBCAT_CD]  VARCHAR (2)   NULL,
    [TCI_LINKG_CD_TITLE] VARCHAR (3)   NULL,
    [TCI_SOC]            VARCHAR (3)   NULL,
    [JGT_JOB_GROUP_ID]   VARCHAR (3)   NULL,
    [TCI_OVRTM_EXMPT_CD] VARCHAR (1)   NULL,
    [TCI_EFFECTIVE_DATE] DATETIME      NULL,
    [UPDT_TIMESTAMP]     DATETIME      NULL
);

