CREATE TABLE [dbo].[Persons] (
    [EmployeeID]               CHAR (9)     NOT NULL,
    [FirstName]                VARCHAR (30) NULL,
    [MiddleName]               VARCHAR (30) NULL,
    [LastName]                 VARCHAR (30) NULL,
    [FullName]                 VARCHAR (50) NULL,
    [Suffix]                   VARCHAR (4)  NULL,
    [BirthDate]                DATETIME     NULL,
    [UCDMailID]                VARCHAR (32) NULL,
    [UCDLoginID]               VARCHAR (8)  NULL,
    [HomeDepartment]           VARCHAR (6)  NULL,
    [AlternateDepartment]      VARCHAR (6)  NULL,
    [AdministrativeDepartment] VARCHAR (6)  NULL,
    [SchoolDivision]           VARCHAR (2)  NULL,
    [PrimaryTitle]             VARCHAR (4)  NULL,
    [PrimaryApptNo]            VARCHAR (2)  NULL,
    [PrimaryDistNo]            VARCHAR (2)  NULL,
    [JobGroupID]               VARCHAR (3)  NULL,
    [HireDate]                 DATETIME     NULL,
    [OriginalHireDate]         DATETIME     NULL,
    [EmployeeStatus]           CHAR (1)     NULL,
    [StudentStatus]            CHAR (1)     NULL,
    [EducationLevel]           CHAR (1)     NULL,
    [BarganingUnit]            VARCHAR (2)  NULL,
    [LeaveServiceCredit]       SMALLINT     NULL,
    [Supervisor]               CHAR (1)     NULL,
    [LastChangeDate]           DATETIME     NULL,
    [IsInPPS]                  BIT          NULL
);

