ALTER TABLE [dbo].[204AcctXProj]
    ADD CONSTRAINT [PK_204AcctXProj] PRIMARY KEY CLUSTERED ([pk] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

