ALTER TABLE [dbo].[204Exclusions]
    ADD CONSTRAINT [PK_204Exclusions] PRIMARY KEY CLUSTERED ([AwardNumber] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

