ALTER TABLE [dbo].[2012ReportingCheckList]
    ADD CONSTRAINT [PK_2012ReportingCheckList_copy] PRIMARY KEY CLUSTERED ([Id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

