ALTER TABLE [dbo].[Associations]
    ADD CONSTRAINT [PK_Associations] PRIMARY KEY CLUSTERED ([ExpenseID] ASC, [OrgR] ASC, [Accession] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

