ALTER TABLE [dbo].[Acct_SFN]
    ADD CONSTRAINT [PK_Acct_SFN_1] PRIMARY KEY CLUSTERED ([chart] ASC, [acct_id] ASC, [isCE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

