ALTER TABLE [dbo].[CESList]
    ADD CONSTRAINT [PK_CESList] PRIMARY KEY CLUSTERED ([idCE] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

