ALTER TABLE [dbo].[Expenses_CE_Nonsalary]
    ADD CONSTRAINT [PK_Expenses_CE_Nonsalary] PRIMARY KEY CLUSTERED ([pk] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

