ALTER TABLE [dbo].[Expenses_PPS]
    ADD CONSTRAINT [PK_Expenses_PPS] PRIMARY KEY CLUSTERED ([idExpenses_PPS] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

