ALTER TABLE [dbo].[Expenses_CAES]
    ADD CONSTRAINT [PK_Expenses_CAES] PRIMARY KEY CLUSTERED ([idExpense] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

