ALTER TABLE [dbo].[Expenses_Field_Stations]
    ADD CONSTRAINT [PK_Expenses_Field_Stations] PRIMARY KEY CLUSTERED ([idFieldStationExpense] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

