ALTER TABLE [dbo].[ExpiredProjectCrossReference]
    ADD CONSTRAINT [PK_ExpiredProjectCrossReference] PRIMARY KEY CLUSTERED ([RemapID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

