ALTER TABLE [dbo].[AllOrgXOrgR]
    ADD CONSTRAINT [PK_OrgXOrgR] PRIMARY KEY CLUSTERED ([Chart] ASC, [Org] ASC, [OrgR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

