ALTER TABLE [dbo].[ProjectStatusCode]
    ADD CONSTRAINT [PK_ProjectStatusCode] PRIMARY KEY CLUSTERED ([Cd] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

