ALTER TABLE [dbo].[AllProjects]
    ADD CONSTRAINT [PK_Project] PRIMARY KEY CLUSTERED ([idProject] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

