ALTER TABLE [dbo].[ProjXOrgR]
    ADD CONSTRAINT [PK_ProjXOrgR] PRIMARY KEY CLUSTERED ([Accession] ASC, [OrgR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

