ALTER TABLE [dbo].[Raw_PPS_Expenses]
    ADD CONSTRAINT [PK_Raw_PPS_Expenses] PRIMARY KEY CLUSTERED ([idPPS_TOE_Raw] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

