ALTER TABLE [dbo].[ReportingOrg]
    ADD CONSTRAINT [PK_ReportingOrg] PRIMARY KEY CLUSTERED ([OrgR] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

