ALTER TABLE [dbo].[SFN_Display]
    ADD CONSTRAINT [PK_SFN_Display] PRIMARY KEY CLUSTERED ([idDisplayLine] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

