CREATE TABLE [dbo].[AssistanceListings_DataGov_PUBLIC_CURRENT] (
    [_Program_Title_]                                   NVARCHAR (MAX) NULL,
    [_Program_Number_]                                  NVARCHAR (50)  NOT NULL,
    [_Popular_Name__020__]                              NVARCHAR (MAX) NULL,
    [_Federal_Agency__030__]                            NVARCHAR (MAX) NULL,
    [_Authorization__040__]                             NVARCHAR (MAX) NULL,
    [_Objectives__050__]                                NVARCHAR (MAX) NULL,
    [_Types_of_Assistance__060__]                       NVARCHAR (MAX) NULL,
    [_Uses_and_Use_Restrictions__070__]                 NVARCHAR (MAX) NULL,
    [_Applicant_Eligibility__081__]                     NVARCHAR (MAX) NULL,
    [_Beneficiary_Eligibility__082__]                   NVARCHAR (MAX) NULL,
    [_Credentials_Documentation__083__]                 NVARCHAR (MAX) NULL,
    [_Preapplication_Coordination__091__]               NVARCHAR (MAX) NULL,
    [_Application_Procedures__092__]                    NVARCHAR (MAX) NULL,
    [_Award_Procedure__093__]                           NVARCHAR (MAX) NULL,
    [_Deadlines__094__]                                 NVARCHAR (MAX) NULL,
    [_Range_of_Approval_Disapproval_Time__095__]        NVARCHAR (MAX) NULL,
    [_Appeals__096__]                                   NVARCHAR (MAX) NULL,
    [_Renewals__097__]                                  NVARCHAR (MAX) NULL,
    [_Formula_and_Matching_Requirements__101__]         NVARCHAR (MAX) NULL,
    [_Length_and_Time_Phasing_of_Assistance__102__]     NVARCHAR (MAX) NULL,
    [_Reports__111__]                                   NVARCHAR (MAX) NULL,
    [_Audits__112__]                                    NVARCHAR (MAX) NULL,
    [_Records__113__]                                   NVARCHAR (MAX) NULL,
    [_Account_Identification__121__]                    NVARCHAR (MAX) NULL,
    [_Obligations__122__]                               NVARCHAR (MAX) NULL,
    [_Range_and_Average_of_Financial_Assistance__123__] NVARCHAR (MAX) NULL,
    [_Program_Accomplishments__130__]                   NVARCHAR (MAX) NULL,
    [_Regulations__Guidelines__and_Literature__140__]   NVARCHAR (MAX) NULL,
    [_Regional_or_Local_Office__151__]                  NVARCHAR (MAX) NULL,
    [_Headquarters_Office__152__]                       NVARCHAR (MAX) NULL,
    [_Website_Address__153__]                           NVARCHAR (MAX) NULL,
    [_Related_Programs__160__]                          NVARCHAR (MAX) NULL,
    [_Examples_of_Funded_Projects__170__]               NVARCHAR (MAX) NULL,
    [_Criteria_for_Selecting_Proposals__180__]          NVARCHAR (MAX) NULL,
    [_Published_Date_]                                  NVARCHAR (MAX) NULL,
    [_Parent_Shortname_]                                NVARCHAR (MAX) NULL,
    [_URL_]                                             NVARCHAR (MAX) NULL,
    [_Recovery_]                                        NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_AssistanceListings_DataGov_PUBLIC_CURRENT] PRIMARY KEY CLUSTERED ([_Program_Number_] ASC)
);

