CREATE TABLE [dbo].[RICE_UC_KRIM_PERSON] (
    [PRNCPL_ID]         VARCHAR (40)  NULL,
    [PRNCPL_NM]         VARCHAR (100) NOT NULL,
    [ENTITY_ID]         VARCHAR (40)  NULL,
    [LDAP_UID_NBR]      VARCHAR (40)  NULL,
    [MOTHRA_ID]         VARCHAR (40)  NULL,
    [COMP_ACCT_USER_ID] VARCHAR (100) NOT NULL,
    [FIRST_NM]          VARCHAR (40)  NULL,
    [MIDDLE_NM]         VARCHAR (40)  NULL,
    [LAST_NM]           VARCHAR (80)  NULL,
    [PERSON_NM]         VARCHAR (124) NULL,
    [EMAIL_ADDR]        VARCHAR (200) NULL,
    [PHONE_NBR]         VARCHAR (20)  NULL,
    [EMPLOYEE_ID]       VARCHAR (100) NULL,
    [PPS_ID]            VARCHAR (100) NULL,
    [STUDENT_ID]        VARCHAR (100) NULL,
    [PIDM]              VARCHAR (100) NULL,
    [DAFIS_ID]          VARCHAR (100) NULL,
    [STAFF_IND]         VARCHAR (1)   NULL,
    [FACULTY_IND]       VARCHAR (1)   NULL,
    [STUDENT_IND]       VARCHAR (1)   NULL,
    [AFFILIATE_IND]     VARCHAR (1)   NULL,
    [PRMRY_DEPT_CD]     VARCHAR (40)  NULL,
    [EMP_STAT_CD]       VARCHAR (40)  NULL,
    [ACTV_IND]          VARCHAR (1)   NULL,
    [LAST_UPDT_DT]      DATETIME2 (7) NULL
);


GO
CREATE NONCLUSTERED INDEX [RICE_UC_KRIM_PERSON_PERSON_NM_NCLINDX]
    ON [dbo].[RICE_UC_KRIM_PERSON]([PERSON_NM] ASC);


GO
CREATE UNIQUE NONCLUSTERED INDEX [RICE_UC_KRIM_PERSON_ COMP_ACCT_USER_ID_NCLIDX]
    ON [dbo].[RICE_UC_KRIM_PERSON]([COMP_ACCT_USER_ID] ASC);

