CREATE CLUSTERED INDEX [TransLogLoad_YearPeriodChartLevel3Org_CLDX]
    ON [dbo].[TransLogLoad]([FiscalYear] DESC, [FiscalPeriod] ASC, [Chart] ASC, [Level3_OrgCode] ASC, [PartitionColumn] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0);

