#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
DEPLOY_SCRIPT="$SCRIPT_DIR/deploy.sh"

APP_NAME="${APP_NAME:-ad419}"
ENVIRONMENT="prod"
DEPLOYMENT_NAME="${DEPLOYMENT_NAME:-${APP_NAME}-${ENVIRONMENT}}"
SUBSCRIPTION_ID="${SUBSCRIPTION_ID:-${PROD_AZURE_SUBSCRIPTION_ID:-}}"
EXPECTED_SUBSCRIPTION_ID="${EXPECTED_SUBSCRIPTION_ID:-${PROD_AZURE_SUBSCRIPTION_ID:-}}"

env \
  SUBSCRIPTION_NAME="${SUBSCRIPTION_NAME:-}" \
  SUBSCRIPTION_ID="$SUBSCRIPTION_ID" \
  EXPECTED_SUBSCRIPTION_ID="$EXPECTED_SUBSCRIPTION_ID" \
  EXPECTED_ENVIRONMENT="$ENVIRONMENT" \
  RESOURCE_GROUP="${RESOURCE_GROUP:-rg-ad419-prod}" \
  LOCATION="${LOCATION:-westus2}" \
  APP_NAME="$APP_NAME" \
  ENVIRONMENT="$ENVIRONMENT" \
  DEPLOYMENT_NAME="$DEPLOYMENT_NAME" \
  SQL_ADMIN_LOGIN="${SQL_ADMIN_LOGIN:-ad419}" \
  SQL_ADMIN_PASSWORD="${SQL_ADMIN_PASSWORD:-}" \
  NOTIFICATION_BASE_URL="${NOTIFICATION_BASE_URL:-}" \
  "$DEPLOY_SCRIPT"
