CREATE UNIQUE NONCLUSTERED INDEX [Raw_PPS_Expenses_EIDOrgAcctSubAcctObjConsolTitleCd_UDX]
    ON [dbo].[Raw_PPS_Expenses]([EID] ASC, [Org] ASC, [Account] ASC, [SubAcct] ASC, [ObjConsol] ASC, [Object] ASC, [TitleCd] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF, ONLINE = OFF, MAXDOP = 0)
    ON [PRIMARY];

