ALTER TABLE [dbo].[AccountType]
    ADD CONSTRAINT [PK_AccountType] PRIMARY KEY CLUSTERED ([AccountType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

