ALTER TABLE [dbo].[ARC_Codes]
    ADD CONSTRAINT [PK_ARC_Codes] PRIMARY KEY CLUSTERED ([ARC_Cd] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

