ALTER TABLE [dbo].[BillingIDConversions]
    ADD CONSTRAINT [PK_BillingIDConversions_1] PRIMARY KEY CLUSTERED ([BillingID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

