ALTER TABLE [dbo].[BalanceTypes]
    ADD CONSTRAINT [PK_Ballance_Type] PRIMARY KEY CLUSTERED ([BalanceTypeCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

