ALTER TABLE [dbo].[BaseBudgetSubFundGroups]
    ADD CONSTRAINT [PK_BaseBudgetSubFundGroups] PRIMARY KEY CLUSTERED ([SubFundGroupNum] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

