ALTER TABLE [dbo].[DocumentTypes]
    ADD CONSTRAINT [PK_DocumentTypes] PRIMARY KEY CLUSTERED ([DocumentType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

