ALTER TABLE [dbo].[FunctionCode]
    ADD CONSTRAINT [PK_FunctionCode] PRIMARY KEY CLUSTERED ([FunctionCodeID] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

