ALTER TABLE [dbo].[FundGroups]
    ADD CONSTRAINT [PK_FundGroups] PRIMARY KEY CLUSTERED ([FundGroup] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

