ALTER TABLE [dbo].[HigherEducationFunctionCodes]
    ADD CONSTRAINT [PK_HigherEducationFunctionCode] PRIMARY KEY CLUSTERED ([HigherEducationFunctionCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

