ALTER TABLE [dbo].[OPFund]
    ADD CONSTRAINT [PK_OPFund_1] PRIMARY KEY CLUSTERED ([Year] ASC, [Period] ASC, [Chart] ASC, [FundNum] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

