ALTER TABLE [dbo].[ObjectSubTypes]
    ADD CONSTRAINT [PK_ObjectSubType] PRIMARY KEY CLUSTERED ([ObjectSubType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

