ALTER TABLE [dbo].[Objects]
    ADD CONSTRAINT [PK_Objects] PRIMARY KEY CLUSTERED ([Year] ASC, [Chart] ASC, [Object] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

