ALTER TABLE [dbo].[SubFundGroups]
    ADD CONSTRAINT [PK_SubFundGroups] PRIMARY KEY CLUSTERED ([Year] ASC, [Period] ASC, [SubFundGroupNum] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

