ALTER TABLE [dbo].[SubFundGroupTypes]
    ADD CONSTRAINT [PK_SubFundGroupTypes_1] PRIMARY KEY CLUSTERED ([SubFundGroupType] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

