CREATE TABLE [dbo].[CsTrackingEntryActive] (
    [OpLocationCode]         NCHAR (1)       NULL,
    [OpFundNum]              NCHAR (5)       NULL,
    [TrackingEntryId]        INT             NOT NULL,
    [VersionNum]             NVARCHAR (25)   NOT NULL,
    [TrackingEntryTypeCode]  NCHAR (1)       NOT NULL,
    [Chart]                  NVARCHAR (2)    NULL,
    [Account]                NVARCHAR (7)    NULL,
    [SubAccount]             NVARCHAR (5)    NULL,
    [Object]                 NVARCHAR (4)    NULL,
    [SubObject]              NVARCHAR (4)    NULL,
    [Project]                NVARCHAR (10)   NULL,
    [ReferenceNum]           NVARCHAR (8)    NULL,
    [TrackingNum]            NVARCHAR (10)   NULL,
    [TrackingEntryDesc]      NVARCHAR (40)   NULL,
    [CostSharingPercent]     NUMERIC (7, 4)  NULL,
    [CostSharingLimitAmount] NUMERIC (15, 2) NULL,
    [EmployeeId]             NVARCHAR (9)    NULL,
    [StartFiscalYear]        NUMERIC (4)     NULL,
    [EndFiscalYear]          NUMERIC (4)     NULL,
    [StartFiscalPeriod]      NCHAR (2)       NULL,
    [EndFiscalPeriod]        NCHAR (2)       NULL,
    [PayrollPercentTypeFlag] NCHAR (1)       NULL,
    [CreateDate]             DATETIME2 (7)   NOT NULL,
    [CreateUserId]           NVARCHAR (10)   NULL,
    [LastUpdateUserId]       NVARCHAR (10)   NULL,
    [LastUpdateDate]         DATETIME2 (7)   NULL,
    [RemovedFlag]            DATETIME2 (7)   NULL,
    [UsedFlag]               NCHAR (1)       NULL,
    [IsActive]               BIT             NULL,
    CONSTRAINT [PK_CsTrackingEntryActive] PRIMARY KEY CLUSTERED ([TrackingEntryId] ASC, [VersionNum] ASC, [TrackingEntryTypeCode] ASC, [CreateDate] ASC)
);

