CREATE TABLE [dbo].[EngineeringOrgs] (
    [Year]           NUMERIC (4)   NOT NULL,
    [Period]         VARCHAR (2)   NOT NULL,
    [Org]            VARCHAR (4)   NOT NULL,
    [Chart]          VARCHAR (2)   NOT NULL,
    [Level]          NUMERIC (2)   NULL,
    [Name]           VARCHAR (40)  NULL,
    [Type]           VARCHAR (4)   NULL,
    [BeginDate]      VARCHAR (19)  NULL,
    [EndDate]        VARCHAR (19)  NULL,
    [HomeDeptNum]    VARCHAR (6)   NULL,
    [HomeDeptName]   VARCHAR (40)  NULL,
    [UpdateDate]     VARCHAR (19)  NULL,
    [Chart1]         VARCHAR (2)   NULL,
    [Org1]           VARCHAR (4)   NULL,
    [Name1]          VARCHAR (40)  NULL,
    [Chart2]         VARCHAR (2)   NULL,
    [Org2]           VARCHAR (4)   NULL,
    [Name2]          VARCHAR (40)  NULL,
    [Chart3]         VARCHAR (2)   NULL,
    [Org3]           VARCHAR (4)   NULL,
    [Name3]          VARCHAR (40)  NULL,
    [Chart4]         VARCHAR (2)   NULL,
    [Org4]           VARCHAR (4)   NULL,
    [Name4]          VARCHAR (40)  NULL,
    [Chart5]         VARCHAR (2)   NULL,
    [Org5]           VARCHAR (4)   NULL,
    [Name5]          VARCHAR (40)  NULL,
    [Chart6]         VARCHAR (2)   NULL,
    [Org6]           VARCHAR (4)   NULL,
    [Name6]          VARCHAR (40)  NULL,
    [Chart7]         VARCHAR (2)   NULL,
    [Org7]           VARCHAR (4)   NULL,
    [Name7]          VARCHAR (40)  NULL,
    [Chart8]         VARCHAR (2)   NULL,
    [Org8]           VARCHAR (4)   NULL,
    [Name8]          VARCHAR (40)  NULL,
    [Chart9]         VARCHAR (2)   NULL,
    [Org9]           VARCHAR (4)   NULL,
    [Name9]          VARCHAR (40)  NULL,
    [Chart10]        VARCHAR (2)   NULL,
    [Org10]          VARCHAR (4)   NULL,
    [Name10]         VARCHAR (40)  NULL,
    [Chart11]        VARCHAR (2)   NULL,
    [Org11]          VARCHAR (4)   NULL,
    [Name11]         VARCHAR (40)  NULL,
    [Chart12]        VARCHAR (2)   NULL,
    [Org12]          VARCHAR (4)   NULL,
    [Name12]         VARCHAR (40)  NULL,
    [ActiveInd]      VARCHAR (1)   NULL,
    [OrganizationPK] VARCHAR (51)  NULL,
    [LastUpdateDate] DATETIME2 (7) NULL
);

