CREATE TABLE [dbo].[ErsEarnings] (
    [PayrollCycleEndDate]        DATETIME2 (7)  NOT NULL,
    [PayrollCycleCode]           NCHAR (2)      NOT NULL,
    [EmployeeId]                 NCHAR (9)      NOT NULL,
    [RecordTypeCode]             NCHAR (2)      NOT NULL,
    [PriGrossControlCode]        NCHAR (3)      NOT NULL,
    [EntrySequenceNum]           NUMERIC (3)    NOT NULL,
    [ErnFAU]                     NCHAR (30)     NULL,
    [TransCode]                  NCHAR (2)      NULL,
    [PayrollScheduleCode]        NCHAR (1)      NULL,
    [PayrollRateTypeCode]        NCHAR (1)      NULL,
    [PayrollPeriodEndDate]       DATETIME2 (7)  NOT NULL,
    [PaidHours]                  NUMERIC (5, 2) NULL,
    [PaidAmount]                 NUMERIC (7, 2) NULL,
    [PaidPercent]                NUMERIC (5, 4) NULL,
    [PayRate]                    NUMERIC (9, 4) NULL,
    [TitleCode]                  NCHAR (4)      NULL,
    [TitleCodeName]              NVARCHAR (30)  NULL,
    [ExceptionInd]               NCHAR (1)      NULL,
    [AcademicAppointmentInd]     NCHAR (1)      NULL,
    [TitleCodeAcademicApptBasis] NCHAR (1)      NULL,
    [TitleCodeAcadPayrollPeriod] NCHAR (1)      NULL,
    [DistDescOfService]          NCHAR (3)      NULL,
    [DescOfServiceTileCode]      NCHAR (1)      NULL,
    [DescOfServicePayCategory]   NCHAR (1)      NULL,
    [ErnDerivedPct]              NUMERIC (5, 4) NULL,
    [ClassTitleOutline]          NCHAR (3)      NULL,
    [ConsumedInd]                NCHAR (1)      NOT NULL
);

