-- =============================================
-- Author:		Ken Taylor
-- Create date: November 26, 2014
-- Description:	Load PI_Name_Exceptions table with any 241 
-- employees that do not already have a PI_Match.
-- Modifications:
-- 2015-03-31 by kjt:  Removed any [AD419] database specific references so that this sproc can be used with other databases
--		such as [AD419_2014], etc. 
-- =============================================
CREATE PROCEDURE [dbo].[usp_LoadPI_Name_Exceptions] 
	@IsDebug bit = 0  --Set this to 1 to display results generated by procedure only.  No changes will be made to the tables.
AS
BEGIN
	-- SET NOCOUNT ON added to prevent extra result sets from
	-- interfering with SELECT statements.
	SET NOCOUNT ON;

  DECLARE @Table TABLE (
	OrgR varchar(4), 
	EmployeeName varchar(200), 
	EID varchar(50), 
	PI varchar(200), 
	LastName varchar(100), 
	FirstMiddle varchar(50),
	FirstInitial varchar(5),
	MiddleInitial varchar(5),
	FirstPortionOfLastName varchar(50),
	ModifiedPIName varchar(200)) 

  -- Note: Cursor automatically takes care of removing hyphens from names with to match names with
  -- missing hyphens like O'Malley to OMalley.
  DECLARE myCursor CURSOR FOR SELECT 
	   REPLACE(SUBSTRING(PI, 0, CHARINDEX(', ',PI, 1) -1), '''', '') + '%' LastName
  FROM [dbo].[PI_Match]
  where PI_MATCH IS NULL

  -- Loop through each of the names with no corresponding PI match value and insert into the table variable,
  -- setting the Lastname and First(Name)Middle(Initial) fields. 
  DECLARE @LastName varchar(100)
  OPEN myCursor
  FETCH NEXT FROM myCursor INTO @LastName
  WHILE @@FETCH_STATUS <> -1
  BEGIN
	INSERT INTO @Table (OrgR, EmployeeName, EID, PI, LastName, FirstMiddle)
	SELECT  [OrgR]
      ,[EmployeeName]
      ,[EID]
      ,[PI]
	  , SUBSTRING(EmployeeName, 0, CHARINDEX(',', EmployeeName, 1)) LastName
	  , SUBSTRING(EmployeeName, CHARINDEX(',', EmployeeName, 1) + 1, 75) FirstMiddle

  FROM [dbo].[PI_Names]
  Where employeename like @LastName
	FETCH NEXT FROM myCursor INTO @LastName
  END
  CLOSE myCursor
  DEALLOCATE myCUrsor
  
  IF @IsDebug = 1
	BEGIN
	  -- Add some dummy entries for testing names like MC/MAC and JOHNS-HOPKINS:
	  INSERT INTO @Table (OrgR, EmployeeName, EID, PI)
	  VALUES 
	  ('ABCD', UPPER('Mc Nalley,Sam P'), '0123456789', UPPER('Mc Nalley, S P')), 
	  ('ABCD', UPPER('Johns-Hopkins,Stuart W'), '0123456789', UPPER('Johns-Hopkins, S P'))

	  UPDATE @Table SET LastName = SUBSTRING(EmployeeName, 0, CHARINDEX(',', EmployeeName, 0)), 
	  FirstMiddle = SUBSTRING(EmployeeName, CHARINDEX(',', EmployeeName, 0) + 1, 75)
	  WHERE LastName IS NULL
	END

  -- Set the first initial:
  UPDATE @Table
  SET FirstInitial = SUBSTRING(FirstMiddle, 1 ,1)

  -- Set the middle initial:
  -- Use the first initial of the first/middle, i.e., "John P", and the middle initial unless there's a hyphen in the first name, i.e., "C-Y Carol".
  -- If there's a hyphen in the "firstname" then assume it's first initial<dash>middle initial, followed by a nick name, as in
  -- "C-Y Carol", where the first initial is "C", and the middle initial is "Y".
  UPDATE @Table 
  SET [MiddleInitial] = CASE WHEN CHARINDEX('-', FirstMiddle, 1) > 0 THEN SUBSTRING(FirstMiddle,  CHARINDEX('-', FirstMiddle, 1) + 1, 1) 
	   ELSE 
			CASE WHEN CHARINDEX(' ', FirstMiddle, 1 ) > 0 THEN SUBSTRING(FirstMiddle, CHARINDEX(' ', FirstMiddle, 1) +1, 1) ELSE NULL END
	   END
  
  /*
  Things to consider:
  1. "Mc/Mac Whatever" should return "McWhatever", etc.
  2. "Johns-Hopkins" should return "Johns"
  3. "OTEIZA DE FRAGA" should return "OTEIZA"
  */
  -- Use first portion of last name if multiple names separated by spaces, i.e. "OTEIZA DE FRAGA":
  UPDATE @Table 
  SET FirstPortionOfLastName = 
	CASE WHEN CHARINDEX(' ', LastName, 1) > 0 THEN 
		CASE WHEN -- starts with Mc, Mac, Van or Von 
			(CHARINDEX('MAC ', LastName, 1) > 0 OR
			CHARINDEX('MC ', LastName, 1) > 0 OR
			CHARINDEX('VAN ', LastName, 1) > 0 OR
			CHARINDEX('VON ', LastName, 1) > 0) THEN
				-- Remove space
				REPLACE(LastName, ' ', '')			
			ELSE -- This must be an other type of multi-part last name
				-- Take first part of last name and call it a day
				SUBSTRING(LastName, 0, CHARINDEX(' ', LastName, 1))
		END 
		WHEN CHARINDEX('-', LastName, 1) > 0 THEN 
			-- Take first part of last name and call it a day
			SUBSTRING(LastName, 0, CHARINDEX('-', LastName, 1))
		ELSE -- Just use the last name the way it is.
			LastName
	END 

  -- Set the ModifiedPIName:
  UPDATE @Table 
  SET ModifiedPIName = CASE WHEN MiddleInitial IS NULL THEN FirstPortionOfLastName + ', ' + FirstInitial ELSE
	  FirstPortionOfLastName + ', ' + FirstInitial  + ' ' + MiddleInitial END

  IF @IsDebug = 1
	BEGIN
		SELECT  DISTINCT 
		   [OrgR]
		  ,[EmployeeName]
		  ,[EID]
		  ,[PI]
		  ,[LastName]
		  ,[FirstMiddle]
		  ,[FirstInitial]
		  ,[MiddleInitial]
		  ,[FirstPortionOfLastName]
		  ,[ModifiedPIName]
  FROM @Table
  ORDER BY [OrgR], [EmployeeName]
	END
  ELSE
	BEGIN
		TRUNCATE TABLE dbo.PI_Name_Exceptions

		--Insert INTO [DBO].[PI_Name_Exceptions] table:
		INSERT INTO [DBO].[PI_Name_Exceptions]
		SELECT DISTINCT * FROM @Table ORDER BY PI , OrgR 

		SELECT  
		   [OrgR]
		  ,[EmployeeName]
		  ,[EID]
		  ,[PI]
		  ,[LastName]
		  ,[FirstMiddle]
		  ,[FirstInitial]
		  ,[MiddleInitial]
		  ,[FirstPortionOfLastName]
		  ,[ModifiedPIName]
	  FROM [dbo].[PI_Name_Exceptions]
	END
    
	SET NOCOUNT OFF;
END