ALTER TABLE [dbo].[sysdiagrams]
    ADD CONSTRAINT [PK__sysdiagr__C2B05B612334397B] PRIMARY KEY CLUSTERED ([diagram_id] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

