ALTER TABLE [dbo].[Appointments]
    ADD CONSTRAINT [PK_Appointments] PRIMARY KEY CLUSTERED ([EmployeeID] ASC, [ApptNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

