ALTER TABLE [dbo].[Distributions]
    ADD CONSTRAINT [PK_Distributions] PRIMARY KEY CLUSTERED ([EmployeeID] ASC, [DistNo] ASC, [ApptNo] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

