ALTER TABLE [dbo].[Titles]
    ADD CONSTRAINT [PK_Titles] PRIMARY KEY CLUSTERED ([TitleCode] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

