CREATE TYPE [dbo].[tt_example] AS  TABLE (
    [PKTrans]           VARCHAR (200)   NOT NULL,
    [Year]              INT             NOT NULL,
    [Period]            CHAR (2)        NOT NULL,
    [Chart]             VARCHAR (2)     NOT NULL,
    [OrgID]             CHAR (4)        NULL,
    [AccountType]       CHAR (2)        NULL,
    [Account]           CHAR (7)        NOT NULL,
    [SubAccount]        CHAR (5)        NOT NULL,
    [ObjectTypeCode]    CHAR (2)        NULL,
    [Object]            CHAR (4)        NOT NULL,
    [SubObject]         CHAR (3)        NOT NULL,
    [BalType]           CHAR (2)        NOT NULL,
    [DocType]           CHAR (4)        NULL,
    [DocOrigin]         CHAR (2)        NOT NULL,
    [DocNum]            CHAR (9)        NOT NULL,
    [DocTrackNum]       CHAR (10)       NULL,
    [InitrID]           CHAR (8)        NULL,
    [InitDate]          SMALLDATETIME   NULL,
    [LineSquenceNumber] DECIMAL (7)     NOT NULL,
    [LineDesc]          VARCHAR (40)    NULL,
    [LineAmount]        DECIMAL (15, 2) NULL,
    [Project]           CHAR (10)       NULL,
    [OrgRefNum]         CHAR (8)        NULL,
    [PriorDocTypeNum]   CHAR (4)        NULL,
    [PriorDocOriginCd]  CHAR (2)        NULL,
    [PriorDocNum]       CHAR (9)        NULL,
    [EncumUpdtCd]       CHAR (1)        NULL,
    [CreationDate]      SMALLDATETIME   NOT NULL,
    [PostDate]          SMALLDATETIME   NOT NULL,
    [ReversalDate]      SMALLDATETIME   NULL,
    [ChangeDate]        SMALLDATETIME   NULL,
    [SrcTblCd]          CHAR (1)        NULL,
    [OrganizationFK]    VARCHAR (14)    NULL,
    [AccountsFK]        VARCHAR (17)    NULL,
    [ObjectsFK]         VARCHAR (11)    NULL,
    [SubObjectFK]       VARCHAR (28)    NULL,
    [SubAccountFK]      VARCHAR (23)    NULL,
    [ProjectFK]         VARCHAR (21)    NULL,
    [IsCAES]            TINYINT         NULL,
    PRIMARY KEY CLUSTERED ([Year] ASC, [Period] ASC, [Chart] ASC, [Account] ASC, [SubAccount] ASC, [Object] ASC, [SubObject] ASC, [BalType] ASC, [DocOrigin] ASC, [DocNum] ASC, [LineSquenceNumber] ASC, [PostDate] ASC));

