CREATE Procedure [dbo].[usp_DownloadDepartments]

AS

DECLARE @MaxDate DATETIME
SET @MaxDate = (SELECT MAX(LastActionDate) FROM Departments)

SELECT * FROM OPENQUERY(PAY_PERS_EXTR, '
	SELECT HME_DEPT_NO, HME_DEPT_NAME, HME_ABRV_DEPT_NAME, UCD_SCHOOL_DIVISION, HME_DEPT_MAIL_CODE, HME_ORG_UNIT_CD, HME_LAST_ACTION_DT FROM PAYROLL.CTVHME
')
WHERE @MaxDate IS NULL OR HME_LAST_ACTION_DT > @MaxDate
