CREATE Procedure [dbo].[usp_DownloadPersons]

AS

DECLARE @MaxDate DATETIME
SET @MaxDate = (SELECT MAX(LastChangeDate) FROM Persons)

SELECT * FROM OPENQUERY(PAY_PERS_EXTR, '
	SELECT EMPLOYEE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMP_NAME, NAMESUFFIX, BIRTH_DATE,
				UCD_MAILID, UCDLOGINID, HOME_DEPT, ALT_DEPT_CD, UCD_ADMIN_DEPT, SCHOOL_DIVISION,
				PRIMARY_TITLE, PRIMARY_APPT_NUM, PRIMARY_DIST_NUM, JOB_GROUP_ID, HIRE_DATE, ORIG_HIRE_DATE,
				EMP_STATUS, STUDENT_STATUS, EDU_LEVEL, EMP_REL_UNIT, EMPLMT_CREDIT, SUPERVISOR, LAST_CHG_DATE
	FROM EDBPER_V
')
WHERE @MaxDate IS NULL OR LAST_CHG_DATE > @MaxDate
