CREATE Procedure [dbo].[usp_DownloadAppointments]

AS

SELECT * FROM OPENQUERY(PAY_PERS_EXTR, '
	SELECT EMPLOYEE_ID, APPT_NUM, GRADE, APPT_DEPT, TITLE_CODE, TITLE_UNIT_CODE, ACADEMIC_BASIS, 
			APPT_PAID_OVER, RETIREMENT_CODE, FIXED_VAR_CODE, APPT_TYPE, APPT_ADC_CODE, APPT_WOS_IND, 
			PERSONNEL_PGM, TIME_REPT_CODE, LEAVE_ACRUCODE, APPT_REP_CODE, PERCENT_FULLTIME, PAY_RATE, 
			PAY_SCHEDULE, RATE_CODE, APPT_BEGIN_DATE, APPT_END_DATE, APPT_DURATION
	FROM EDBAPP_V
')
