/*INNER JOIN FISDataMart.dbo.ARCCodes AS AC ON derivedtbl_1.ANNUAL_REPORT_CODE = AC.ARCCode*/
CREATE VIEW dbo.DaFIS_AccountsByARC_v
AS
SELECT        CHART_NUM AS Chart, ACCT_NUM AS Account, ANNUAL_REPORT_CODE AS AnnualReportCode, OP_FUND_NUM AS OpFundNum
FROM            OPENQUERY(FIS_DS, 
                         '
		SELECT Chart_Num, ACCT_NUM, T1.ANNUAL_REPORT_CODE, OP_FUND_NUM 
        FROM FINANCE.ORGANIZATION_ACCOUNT T1
        INNER JOIN  FINANCE.ANNUAL_REPORT_CODE t2 ON T1.ANNUAL_REPORT_CODE = T2.ANNUAL_REPORT_CODE AND T2.ANNUAL_RPT_CATEGORY_CD LIKE ''AEX'' 
            AND UPPER(ANNUAL_REPORT_CODE_NAME) NOT LIKE ''%DO NOT USE%'' 
			AND T2.ANNUAL_REPORT_CODE NOT IN (''440269'',''440275'') AND T2.ANNUAL_REPORT_CODE NOT BETWEEN ''440291'' AND ''440299''
		WHERE FISCAL_YEAR = 9999 AND FISCAL_PERIOD = ''--'' 
        ORDER BY  Chart_Num, ACCT_NUM, T1.ANNUAL_REPORT_CODE, OP_FUND_NUM     
	')
                          AS derivedtbl_1