CREATE TABLE [dbo].[12-13_CE_Report] (
    [Id]                                                               INT            IDENTITY (1, 1) NOT NULL,
    [Dept code]                                                        FLOAT          NULL,
    [Dept Name]                                                        NVARCHAR (255) NULL,
    [PI]                                                               NVARCHAR (255) NULL,
    [Dept level Org]                                                   NVARCHAR (255) NULL,
    [PI FullName]                                                      NVARCHAR (255) NULL,
    [EmployeeID]                                                       NVARCHAR (255) NULL,
    [Project Accession #]                                              NVARCHAR (255) NULL,
    [Projects#Project]                                                 NVARCHAR (255) NULL,
    [% CE Effort towards project;_ Report this as FTE on Line 241 of ] FLOAT          NULL,
    [Full Monthly DistPayRate]                                         NVARCHAR (255) NULL,
    [Full Annual PayRate]                                              FLOAT          NULL,
    [HomeDepartment]                                                   NVARCHAR (255) NULL,
    [TitleCode]                                                        FLOAT          NULL,
    [Total CE FTE]                                                     NVARCHAR (255) NULL,
    [Chart]                                                            NVARCHAR (255) NULL,
    [Account]                                                          NVARCHAR (255) NULL,
    [SubAccount]                                                       NVARCHAR (255) NULL,
    [Object]                                                           NVARCHAR (255) NULL,
    [OPFund]                                                           FLOAT          NULL,
    [F20]                                                              NVARCHAR (255) NULL,
    [F21]                                                              FLOAT          NULL
);

