CREATE TABLE [dbo].[2012_cris_export] (
    [ACCESSION]        NVARCHAR (255) NULL,
    [FIELD2]           NVARCHAR (255) NULL,
    [STATION]          NVARCHAR (255) NULL,
    [PROBLEMS]         NVARCHAR (255) NULL,
    [CHANGED]          NVARCHAR (255) NULL,
    [CHDATE]           DATETIME       NULL,
    [PROJECT]          NVARCHAR (255) NULL,
    [PRGOFRES]         NVARCHAR (255) NULL,
    [PRCHANGES]        NVARCHAR (255) NULL,
    [TITLE]            NVARCHAR (255) NULL,
    [ORG1]             NVARCHAR (255) NULL,
    [ORG2]             NVARCHAR (255) NULL,
    [INV1]             NVARCHAR (255) NULL,
    [INV2]             NVARCHAR (255) NULL,
    [INV3]             NVARCHAR (255) NULL,
    [FUNDTYPE]         NVARCHAR (255) NULL,
    [DEPT]             NVARCHAR (255) NULL,
    [STATUS]           NVARCHAR (255) NULL,
    [CRISSTAT]         NVARCHAR (255) NULL,
    [PROJTYPE]         NVARCHAR (255) NULL,
    [TERMDATE]         DATETIME       NULL,
    [CRISTDATE]        DATETIME       NULL,
    [CRISDATE]         DATETIME       NULL,
    [INV4]             NVARCHAR (255) NULL,
    [INV5]             NVARCHAR (255) NULL,
    [INV6]             NVARCHAR (255) NULL,
    [PCOVERED]         NVARCHAR (255) NULL,
    [BEGINDATE]        DATETIME       NULL,
    [COOPDEPTS]        NVARCHAR (255) NULL,
    [FILEDATE]         DATETIME       NULL,
    [PCONTACT]         NVARCHAR (255) NULL,
    [NONTECH1]         NVARCHAR (255) NULL,
    [NONTECH2]         NVARCHAR (255) NULL,
    [MSTATE]           NVARCHAR (255) NULL,
    [FIELD4]           NVARCHAR (255) NULL,
    [LOCATION]         NVARCHAR (255) NULL,
    [ICTAG]            NVARCHAR (255) NULL,
    [WHYTERM]          NVARCHAR (255) NULL,
    [MEMTDATE]         NVARCHAR (255) NULL,
    [MEMTEXT]          NVARCHAR (255) NULL,
    [CLASS01]          NVARCHAR (255) NULL,
    [CLASS02]          NVARCHAR (255) NULL,
    [CLASS03]          NVARCHAR (255) NULL,
    [CLASS04]          NVARCHAR (255) NULL,
    [CLASS05]          FLOAT          NULL,
    [CLASS06]          FLOAT          NULL,
    [CLASS07]          FLOAT          NULL,
    [CLASS08]          FLOAT          NULL,
    [CLASS09]          FLOAT          NULL,
    [CLASS10]          NVARCHAR (255) NULL,
    [BASIC]            NVARCHAR (255) NULL,
    [APPLIED]          NVARCHAR (255) NULL,
    [DEVELOPMNT]       NVARCHAR (255) NULL,
    [FORESTRYANHEALTH] NVARCHAR (255) NULL,
    [LAST2008]         NVARCHAR (255) NULL,
    [PROPOSAL]         NVARCHAR (255) NULL,
    [OBJNEW]           NVARCHAR (255) NULL,
    [APPNEW]           NVARCHAR (255) NULL,
    [KEYNEW]           NVARCHAR (255) NULL,
    [AMOUNT]           NVARCHAR (255) NULL,
    [GRANTFY]          NVARCHAR (255) NULL,
    [AWARDDATE]        NVARCHAR (255) NULL,
    [REGIONAL]         NVARCHAR (255) NULL
);

