CREATE TABLE [dbo].[ACL3_Admin] (
    [loc]       VARCHAR (2)  NULL,
    [dept]      VARCHAR (3)  NULL,
    [proj]      VARCHAR (4)  NULL,
    [project]   VARCHAR (24) NOT NULL,
    [accession] CHAR (7)     NOT NULL,
    [PI]        VARCHAR (30) NULL,
    [f201]      FLOAT        NULL,
    [f202]      FLOAT        NULL,
    [f203]      FLOAT        NULL,
    [f204]      FLOAT        NULL,
    [f205]      FLOAT        NULL,
    [f231]      FLOAT        NULL,
    [f219]      FLOAT        NULL,
    [f209]      FLOAT        NULL,
    [f310]      FLOAT        NULL,
    [f308]      FLOAT        NULL,
    [f311]      FLOAT        NULL,
    [f316]      FLOAT        NULL,
    [f312]      FLOAT        NULL,
    [f313]      FLOAT        NULL,
    [f314]      FLOAT        NULL,
    [f315]      FLOAT        NULL,
    [f318]      FLOAT        NULL,
    [f332]      FLOAT        NULL,
    [f220]      FLOAT        NULL,
    [f22F]      FLOAT        NULL,
    [f221]      FLOAT        NULL,
    [f222]      FLOAT        NULL,
    [f223]      FLOAT        NULL,
    [f233]      FLOAT        NULL,
    [f234]      FLOAT        NULL,
    [f241]      FLOAT        NULL,
    [f242]      FLOAT        NULL,
    [f243]      FLOAT        NULL,
    [f244]      FLOAT        NULL,
    [f350]      FLOAT        NULL
);

