CREATE TABLE [dbo].[LaborTransactionsAllFields] (
    [UNIV_FISCAL_YR]            NUMERIC (4)     NOT NULL,
    [FIN_COA_CD]                VARCHAR (2)     NULL,
    [ORG_CD]                    VARCHAR (4)     NULL,
    [ACCT_TYP_CD]               VARCHAR (2)     NULL,
    [ACCOUNT_NBR]               VARCHAR (7)     NULL,
    [SUB_ACCT_NBR]              VARCHAR (5)     NULL,
    [FIN_CONS_OBJ_CD]           VARCHAR (4)     NULL,
    [FIN_OBJECT_CD]             VARCHAR (4)     NULL,
    [FINOBJ_FRNGSLRY_CD]        VARCHAR (1)     NULL,
    [FIN_SUB_OBJ_CD]            VARCHAR (4)     NULL,
    [FIN_BALANCE_TYP_CD]        VARCHAR (2)     NULL,
    [FIN_OBJ_TYP_CD]            VARCHAR (2)     NULL,
    [UNIV_FISCAL_PRD_CD]        VARCHAR (2)     NULL,
    [FDOC_TYP_CD]               VARCHAR (4)     NULL,
    [FS_ORIGIN_CD]              VARCHAR (2)     NULL,
    [FDOC_NBR]                  VARCHAR (14)    NULL,
    [TRN_ENTR_SEQ_NBR]          NUMERIC (5)     NULL,
    [POSITION_NBR]              VARCHAR (8)     NULL,
    [PROJECT_CD]                VARCHAR (10)    NULL,
    [TRN_LDGR_ENTR_DESC]        VARCHAR (40)    NULL,
    [TRN_LDGR_ENTR_AMT]         NUMERIC (19, 2) NULL,
    [TRANSACTION_DT]            DATETIME2 (7)   NULL,
    [ORG_DOC_NBR]               VARCHAR (10)    NULL,
    [ORG_REFERENCE_ID]          VARCHAR (8)     NULL,
    [FDOC_REF_TYP_CD]           VARCHAR (4)     NULL,
    [FS_REF_ORIGIN_CD]          VARCHAR (2)     NULL,
    [FDOC_REF_NBR]              VARCHAR (14)    NULL,
    [FDOC_REVERSAL_DT]          DATETIME2 (7)   NULL,
    [TRN_ENCUM_UPDT_CD]         VARCHAR (1)     NULL,
    [TRN_POST_DT]               DATETIME2 (7)   NULL,
    [PAY_PERIOD_END_DT]         DATETIME2 (7)   NULL,
    [TRN_TOTAL_HR]              NUMERIC (8, 2)  NULL,
    [PYRL_DT_FSCL_YR]           NUMERIC (4)     NULL,
    [PYRL_DT_FSCLPRD_CD]        VARCHAR (2)     NULL,
    [EMPLID]                    VARCHAR (40)    NULL,
    [ERNCD]                     VARCHAR (3)     NULL,
    [PAYGROUP]                  VARCHAR (3)     NULL,
    [TIMESTAMP]                 DATETIME2 (7)   NULL,
    [LABOR_TRANSACTION_ID]      NUMERIC (12)    NOT NULL,
    [PARENT_TRANSACTION_ID]     NUMERIC (12)    NULL,
    [PAY_CYCLE_CD]              VARCHAR (2)     NULL,
    [LIEN_START]                VARCHAR (10)    NULL,
    [LIEN_END]                  VARCHAR (10)    NULL,
    [LABOR_TRANSACTION_CD]      VARCHAR (2)     NULL,
    [PRIMARY_GROSS_CTL]         VARCHAR (3)     NULL,
    [HOME_DEPT_CD]              VARCHAR (6)     NULL,
    [PAY_SCHED_CD]              VARCHAR (2)     NULL,
    [RATE_TYPE_CD]              VARCHAR (1)     NULL,
    [DIST_PAY_RATE]             NUMERIC (17, 4) NULL,
    [PAID_PERCENT]              NUMERIC (5, 4)  NULL,
    [PPS_TITLE_CD]              VARCHAR (4)     NULL,
    [RECORD_TYPE]               VARCHAR (2)     NULL,
    [ERN_DERIVED_PERCENT]       NUMERIC (5, 4)  NULL,
    [LEAVE_ASSESS_IND]          VARCHAR (1)     NULL,
    [STUDENT_STATUS]            VARCHAR (1)     NULL,
    [LEAVE_ACCRUAL_CD]          CHAR (1)        NULL,
    [EDB_OBJECT_CD]             VARCHAR (4)     NULL,
    [BENEFIT_GROUP_CD]          VARCHAR (4)     NULL,
    [BENEFIT_SUB_GRP_CD]        VARCHAR (4)     NULL,
    [REVERSAL_IND]              CHAR (1)        NULL,
    [BEN_CAT_CD]                VARCHAR (2)     NULL,
    [RATE_ADJ_IND]              VARCHAR (1)     NULL,
    [REVERSED_IND]              CHAR (1)        NULL,
    [DAFIS_ID]                  VARCHAR (10)    NOT NULL,
    [UCDLOGIN_ID]               VARCHAR (8)     NULL,
    [EMPLOYEE_ID]               VARCHAR (9)     NULL,
    [PRIOR_EMPLOYEE_ID]         VARCHAR (9)     NULL,
    [PERSON_NAME]               VARCHAR (30)    NULL,
    [PERSON_LAST_NAME]          VARCHAR (20)    NULL,
    [PERSON_FIRST_NAME]         VARCHAR (20)    NULL,
    [PERSON_MIDDLE_NAME]        VARCHAR (20)    NULL,
    [EMAIL_ID]                  VARCHAR (44)    NULL,
    [EMPLOYEE_STATUS_CODE]      VARCHAR (1)     NULL,
    [EMPLOYEE_TYPE_CODE]        VARCHAR (1)     NULL,
    [EMPLOYEE_CLIENT_TYPE_CODE] VARCHAR (1)     NULL,
    [EMPLOYEE_CLIENT_TYPE_DESC] VARCHAR (20)    NULL
);

