CREATE TABLE [dbo].[UCD_PERSON] (
    [DAFIS_ID]                  VARCHAR (10) NOT NULL,
    [UCDLOGIN_ID]               VARCHAR (8)  NULL,
    [EMPLOYEE_ID]               VARCHAR (9)  NULL,
    [PRIOR_EMPLOYEE_ID]         VARCHAR (9)  NULL,
    [PERSON_NAME]               VARCHAR (30) NULL,
    [PERSON_LAST_NAME]          VARCHAR (20) NULL,
    [PERSON_FIRST_NAME]         VARCHAR (20) NULL,
    [PERSON_MIDDLE_NAME]        VARCHAR (20) NULL,
    [EMAIL_ID]                  VARCHAR (44) NULL,
    [EMPLOYEE_STATUS_CODE]      VARCHAR (1)  NULL,
    [EMPLOYEE_TYPE_CODE]        VARCHAR (1)  NULL,
    [EMPLOYEE_CLIENT_TYPE_CODE] VARCHAR (1)  NULL,
    [EMPLOYEE_CLIENT_TYPE_DESC] VARCHAR (20) NULL
);

